# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/sueshim/Desktop/cs184/hw2-meshedit-sp24-sueyoungshim/CGL/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/sueshim/Desktop/cs184/hw2-meshedit-sp24-sueyoungshim/CGL/deps/glew/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/sueshim/Desktop/cs184/hw2-meshedit-sp24-sueyoungshim/CGL/deps/glfw/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/sueshim/Desktop/cs184/hw2-meshedit-sp24-sueyoungshim/CGL/deps/glfw/cmake_uninstall.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/sueshim/Desktop/cs184/hw2-meshedit-sp24-sueyoungshim/CGL/deps/glfw/src/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/sueshim/Desktop/cs184/hw2-meshedit-sp24-sueyoungshim/CGL/deps/glfw/src/glfw3.pc.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/sueshim/Desktop/cs184/hw2-meshedit-sp24-sueyoungshim/CGL/deps/glfw/src/glfw3Config.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/sueshim/Desktop/cs184/hw2-meshedit-sp24-sueyoungshim/CGL/deps/glfw/src/glfw_config.h.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/sueshim/Desktop/cs184/hw2-meshedit-sp24-sueyoungshim/CGL/src/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/BasicConfigVersion-SameMajorVersion.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/CMakePackageConfigHelpers.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/CheckCSourceCompiles.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/CheckIncludeFile.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/CheckLibraryExists.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/FindFreetype.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/FindOpenGL.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/FindPackageMessage.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/FindThreads.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/Internal/CheckSourceCompiles.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/WriteBasicConfigVersionFile.cmake))

/Users/sueshim/Desktop/cs184/hw2-meshedit-sp24-sueyoungshim/xcode/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/Cellar/cmake/3.28.1/bin/cmake -S/Users/sueshim/Desktop/cs184/hw2-meshedit-sp24-sueyoungshim -B/Users/sueshim/Desktop/cs184/hw2-meshedit-sp24-sueyoungshim/xcode
